### ISSUE TITLE
Blender 2.82/2.83 compatibility

### ISSUE THREAD

**Issue by xan2622** [MaximeHerpin/Blender_Spiderwebs#4]
Hi.

Do you plan to update the SpiderWebs addon to Blender 2.82/2.83 ?

**Comment by Oxervision** [comment]
Hi,

I have the same question, some news about update to Blender 2.82/2.83

**Comment by Oxervision** [comment]
macOS 10.13.6 & Blender 2.82 & 2.83

Hi again,
I made some changes in the code, I added the addon to the Add Menu and an icon for the addon.
The addon appears in the **Add > Mesh Menu** and the options appear when you call the operator but it gives an error:
```
Error: Traceback (most recent call last):
  File "/Users/User/Library/Application Support/Blender/2.83/scripts/addons/spiderwebs/__init__.py", line 54, in execute
    texture_size=self.texture_size, draw_curve=self.draw_curve, density=self.density, detect_floor=self.detect_floor, randomness=self.randomness)
  File "/Users/Oxer/Library/Application Support/Blender/2.83/scripts/addons/spiderwebs/__init__.py", line 128, in __init__
    self.generate_webs(webs_number)
  File "/Users/User/Library/Application Support/Blender/2.83/scripts/addons/spiderwebs/__init__.py", line 139, in generate_webs
    web = Web(anchor_points_candidates=self.anchor_points, gravity_strength=self.gravity_strength, size=self.size, density=self.density, ground=self.detect_floor, randomness=self.randomness)
  File "/Users/User/Library/Application Support/Blender/2.83/scripts/addons/spiderwebs/__init__.py", line 317, in __init__
    self.ground_z = detect_ground(anchor_points_candidates)
  File "/Users/User/Library/Application Support/Blender/2.83/scripts/addons/spiderwebs/__init__.py", line 969, in detect_ground
    candidate = z_locations[0]
IndexError: list index out of range
```
I'm not an expert in Python, so I can't fix the issue.

![Add Menu](https://user-images.githubusercontent.com/46649474/78394808-9e7dd600-75ec-11ea-81a6-71ea263e1904.jpg)

![Error Report](https://user-images.githubusercontent.com/46649474/78394833-a6d61100-75ec-11ea-9483-6d9c0c36c480.jpg)

Here is the addon with my changes for 2.82 & 2.83, but doesn't work :(

[spiderwebs.zip](https://github.com/MaximeHerpin/Blender_Spiderwebs/files/4429348/spiderwebs.zip)
